#!/usr/bin/env ruby

require "serialist-gen/serialist-gen"

require "json"
require "yaml"
require "pp"
require "trollop"


intermediate_dir = File.expand_path "~/.serialist-tmp"

opts = Trollop::options do

	banner <<-EOS
USAGE: serialist-examine <format file> <binary file> <format name> [options]

where [options] are:
	EOS
end

format_file = ARGV.shift
binary_file = ARGV.shift
format_name = ARGV.shift

if !format_file
	Trollop::die "Please specify a format file"
end

if !binary_file
	Trollop::die "Please specify a binary file"
end

if !format_name
	Trollop::die "Please specify a format name"
end

name = File.basename(format_file).gsub(/\.format$/, "")

source = `serialist-gen #{format_file} -t CJSONSource`
source = <<-SOURCE

#include <iostream>

#{source}

picojson::object write_error_info(SerialistErrorInfo* info, size_t depth)
{
	const wchar_t* member;
	size_t index, count, offset;

	picojson::object curr;
	if (GetSerialistErrorInfo(info, depth, NULL, &member, &index, &count, &offset))
	{
		return curr;
	}

	picojson::object next = write_error_info(info, depth + 1);

	curr[L"member"] = picojson::value(member);
	curr[L"index"] = picojson::value((double)index);
	curr[L"count"] = picojson::value((double)count);
	curr[L"offset"] = picojson::value((double)offset);
	curr[L"parent"] = picojson::value(next);

	return curr;
}

int main(int argc, char** argv)
{
	FILE* fp = fopen("#{binary_file}", "rb");

	#{format_name}* pointer = NULL;
	SerialistErrorInfo* info = NULL;
	CreateSerialistErrorInfo(&info);
	SerialistError err = ReadWithInfo#{format_name}(fp, info, &pointer);

	if (err)
	{
		picojson::object obj;
		obj[L"read_error"] = picojson::value(SerialistErrorWString(err));

		obj[L"stack"] = picojson::value(write_error_info(info, 0));

		picojson::value errval(obj);
		
		std::wcout << errval.serialize() << std::endl;

		return EXIT_FAILURE;
	}

	std::wcout << JSONRead#{format_name}(pointer).serialize() << std::endl;
	fclose(fp);
	return EXIT_SUCCESS;
}

SOURCE

puts "Using intermediate directory: #{File.join(intermediate_dir)}"

FileUtils.mkdir_p File.join(intermediate_dir)

File.write(File.join(intermediate_dir, "main.cpp"), source)

source_file = File.join(intermediate_dir, "#{name}.c")
header_file = File.join(intermediate_dir, "#{name}.h")
exec_file = File.join(intermediate_dir, "parse")

FileUtils.rm source_file if File.exist? source_file
FileUtils.rm header_file if File.exist? header_file
FileUtils.rm exec_file if File.exist? exec_file

c_source = `serialist-gen #{format_file} -t CSource`
File.write(source_file, c_source)

h_source = `serialist-gen #{format_file} -t CHeader`
File.write(header_file, h_source)

FileUtils.cp(File.join(Gem.datadir("serialist-gen"), "picojson.hpp"), File.join(intermediate_dir, "picojson.hpp"))

`cd #{intermediate_dir} && gcc #{File.join(intermediate_dir, name)}.c -c -o #{File.join(intermediate_dir, name)}.o`
`cd #{intermediate_dir} && g++ #{File.join(intermediate_dir, "main.cpp")} #{File.join(intermediate_dir, name)}.o -o #{exec_file}`

output = `#{exec_file} 2>&1`
begin
	x = JSON.parse(output)
	puts x.to_yaml
rescue
	puts "Unhandled Error. Output:"
	puts output
end


